swagger: "2.0"
info:
  description: "BDD Workshop"
  version: "1.0.0"
  title: "BDDWorkshop"
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

paths:
  /test:
    get:
      operationId: "helloworld.get"
      responses:
        200:
          description: "hello, world"

  /feed:
    get:
      operationId: "tweets.get"
      responses:
        200:
          description: "Feed"
    post:
      operationId: "tweets.add"
      responses:
        200:
          description: "Add a tweet"
      consumes:
        - application/json
      parameters:
        - name: "tweet"
          in: body
          required: true
          schema:
            type: object
            required:
              - tweet
            properties:
              tweet:
                type: string

  /followed/{following}/{followed}:
    put:
      operationId: "followed.follow"
      parameters:
        - name: "following"
          in: path
          required: true
          type: string
          format: path
        - name: "followed"
          in: path
          required: true
          type: string
          format: path
      responses:
        200:
          description: "follow a user"
  /followed:
    delete:
      operationId: "followed.delete_all"
      responses:
        200:
          description: "Remove all followed"